version: '3.8'

services:
  bot:
    build: .
    env_file: .env
    depends_on:
      - db
    volumes:
      - ./downloads:/app/downloads
      - ./cookies.txt:/app/cookies.txt

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
